import React from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export const FAQ = () => {
  return (
    <div className="flex flex-col mt-[100px] mb-[300px]">
      <div className="text-center">
        <div className="text-3xl font-bold">FAQ</div>
        <div className="text-[20px] text-[#707070] mt-5">
          Frequently Asked Questions
        </div>
      </div>

      <div className="mt-[74px] w-[550px]">
        <Accordion type="single" collapsible>
          <AccordionItem value="item-1">
            <AccordionTrigger className="text-[20px]  gap-10">
              Are the recipes created by the AI safe to consume?
            </AccordionTrigger>
            <AccordionContent className="text-base text-[#707070]">
              Yes, our top priority is the safety and satisfaction of our users.
              The recipes generated by our AI undergo rigorous quality checks to
              ensure they meet safety standards and are suitable for
              consumption. Additionally, user feedback helps us continually
              improve and refine the recipe generation process.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-2">
            <AccordionTrigger className="text-[20px]  gap-10">
              Are the recipes suitable for beginner cooks?
            </AccordionTrigger>
            <AccordionContent className="text-base text-[#707070]">
              Yes, our top priority is the safety and satisfaction of our users.
              The recipes generated by our AI undergo rigorous quality checks to
              ensure they meet safety standards and are suitable for
              consumption. Additionally, user feedback helps us continually
              improve and refine the recipe generation process.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-3">
            <AccordionTrigger className="text-[20px]  gap-10">
              Are the recipes suitable for special occasions?
            </AccordionTrigger>
            <AccordionContent className="text-base text-[#707070]">
              Yes, our top priority is the safety and satisfaction of our users.
              The recipes generated by our AI undergo rigorous quality checks to
              ensure they meet safety standards and are suitable for
              consumption. Additionally, user feedback helps us continually
              improve and refine the recipe generation process.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-4">
            <AccordionTrigger className="text-[20px]  gap-10">
              Is there a cost to use the app?
            </AccordionTrigger>
            <AccordionContent className="text-base text-[#707070]">
              Yes, our top priority is the safety and satisfaction of our users.
              The recipes generated by our AI undergo rigorous quality checks to
              ensure they meet safety standards and are suitable for
              consumption. Additionally, user feedback helps us continually
              improve and refine the recipe generation process.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  );
};
