import React from "react";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

export const FAQ = () => {
  return (
    <div className="relative min-h-screen w-full flex items-center justify-center bg-cover bg-center bg-no-repeat p-6" 
         style={{ 
           backgroundImage: "url('/assets/faqImage.jpg')",
         }}
    >
      {/* Overlay to reduce the opacity of the background image */}
      <div className="absolute inset-0 "></div>

      {/* Content goes here */}
      <div className="relative flex flex-col mt-[100px] mb-[300px] z-10">
        <div className="text-center">
          <div className="text-3xl font-bold text-white">FAQ</div>
          <div className="text-[20px] text-[#f0f0f0] mt-5">
            Frequently Asked Questions
          </div>
        </div>

        <div className="mt-[74px] w-[550px] bg-white bg-opacity-90 p-8 rounded-lg shadow-lg">
          <Accordion type="single" collapsible>
            <AccordionItem value="item-1">
              <AccordionTrigger className="text-[20px] gap-10">
                Are the recipes created by the AI safe to consume?
              </AccordionTrigger>
              <AccordionContent className="text-base text-[#707070]">
                Yes, our top priority is the safety and satisfaction of our users.
                The recipes generated by our AI undergo rigorous quality checks to
                ensure they meet safety standards and are suitable for
                consumption. Additionally, user feedback helps us continually
                improve and refine the recipe generation process.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-2">
              <AccordionTrigger className="text-[20px] gap-10">
                Are the recipes suitable for beginner cooks?
              </AccordionTrigger>
              <AccordionContent className="text-base text-[#707070]">
                Yes, our top priority is the safety and satisfaction of our users.
                The recipes generated by our AI undergo rigorous quality checks to
                ensure they meet safety standards and are suitable for
                consumption. Additionally, user feedback helps us continually
                improve and refine the recipe generation process.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-3">
              <AccordionTrigger className="text-[20px] gap-10">
                Are the recipes suitable for special occasions?
              </AccordionTrigger>
              <AccordionContent className="text-base text-[#707070]">
                Yes, our top priority is the safety and satisfaction of our users.
                The recipes generated by our AI undergo rigorous quality checks to
                ensure they meet safety standards and are suitable for
                consumption. Additionally, user feedback helps us continually
                improve and refine the recipe generation process.
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-4">
              <AccordionTrigger className="text-[20px] gap-10">
                Is there a cost to use the app?
              </AccordionTrigger>
              <AccordionContent className="text-base text-[#707070]">
                Yes, our top priority is the safety and satisfaction of our users.
                The recipes generated by our AI undergo rigorous quality checks to
                ensure they meet safety standards and are suitable for
                consumption. Additionally, user feedback helps us continually
                improve and refine the recipe generation process.
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </div>
      </div>
    </div>
  );
};

export default FAQ;
