export const CuisineType = [
    { value: "indian", label: "Indian" },
    { value: "italian", label: "Italian" },
    { value: "chinese", label: "Chinese" },
    { value: "mexican", label: "Mexican" },
    { value: "thai", label: "Thai" },
    { value: "japanese", label: "Japanese" },
    { value: "french", label: "French" },
    { value: "mediterranean", label: "Mediterranean" },
    { value: "greek", label: "Greek" },
    { value: "spanish", label: "Spanish" },
    { value: "german", label: "German" },
    { value: "korean", label: "Korean" },
    { value: "vietnamese", label: "Vietnamese" },
    { value: "american", label: "American" },
    { value: "brazilian", label: "Brazilian" },
    { value: "caribbean", label: "Caribbean" },
    { value: "cajun", label: "Cajun" },
    { value: "english", label: "English" },
    { value: "irish", label: "Irish" },
    { value: "russian", label: "Russian" },
    { value: "turkish", label: "Turkish" },
    // Add more cuisine types as needed
];
