
// export const ingredients=[
//     { value: "pasta", label: "Pasta" },
//     { value: "tomato", label: "Tomato" },
//     { value: "chicken", label: "Chicken" },
//     { value: "beef", label: "Beef" },
//     { value: "rice", label: "Rice" },
//     { value: "potato", label: "Potato" },
//     { value: "onion", label: "Onion" },
//     { value: "garlic", label: "Garlic" },
//     { value: "salt", label: "Salt" },
//     { value: "pepper", label: "Pepper" },
//     { value: "olive-oil", label: "Olive Oil" },
//     { value: "butter", label: "Butter" },
//     { value: "milk", label: "Milk" },
//     { value: "flour", label: "Flour" },
//     { value: "sugar", label: "Sugar" },
//     { value: "cheese", label: "Cheese" },
//     { value: "bacon", label: "Bacon" },
//     { value: "eggs", label: "Eggs" },
//     { value: "bread", label: "Bread" },
//     { value: "lettuce", label: "Lettuce" },
//     { value: "cucumber", label: "Cucumber" },
//     { value: "carrot", label: "Carrot" },
//     { value: "apple", label: "Apple" },
//     { value: "banana", label: "Banana" },
//     { value: "orange", label: "Orange" },
//     { value: "lemon", label: "Lemon" },
//     { value: "lime", label: "Lime" },
//     { value: "strawberry", label: "Strawberry" },
//     { value: "blueberry", label: "Blueberry" },
//     { value: "raspberry", label: "Raspberry" },
//     { value: "blackberry", label: "Blackberry" },
//     { value: "pineapple", label: "Pineapple" },
//     { value: "watermelon", label: "Watermelon" },
//     { value: "melon", label: "Melon" },
//     { value: "grape", label: "Grape" },
//     { value: "kiwi", label: "Kiwi" },
//     { value: "mango", label: "Mango" },
//     { value: "peach", label: "Peach" },
//     { value: "pear", label: "Pear" },
//     { value: "plum", label: "Plum" },
//     { value: "apricot", label: "Apricot" },
//     { value: "cherry", label: "Cherry" },
//     { value: "avocado", label: "Avocado" },
// ];
